# Autogenerated wrapper script for rapidjson_jll for any
export rapidjson_h

JLLWrappers.@generate_wrapper_header("rapidjson")
JLLWrappers.@declare_file_product(rapidjson_h)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        rapidjson_h,
        "include/rapidjson/rapidjson.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
